### ISSUE TITLE
Why need vulkan？

### ISSUE THREAD

**Issue by bio-punk** [wkwan7/Category_Level_Manipulation#2]
I run project as：
```
python -m tools.run_rl configs/gail/gail_baseline.py \
 --seed=0 \
 --cfg-options "env_cfg.env_name=OpenCabinetDoor-v0" \
 --work-dir=./work_dirs/gail_baseline_door \
 --num-gpus=3 \
 --clean-up
```
then I got unexpected  output:
```
Process NormalWorker-4:
Traceback (most recent call last):
  File "/data/run01/scv9822/anaconda3/envs/mani-skill/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/run01/scv9822/Category_Level_Manipulation-main/mani_skill_learn/env/parallel_runner.py", line 43, in run
    func = self.cls(*self.args, **self.kwargs)
  File "/data/run01/scv9822/Category_Level_Manipulation-main/mani_skill_learn/env/rollout.py", line 18, in __init__
    self.env = build_env(env_cfg)
  File "/data/run01/scv9822/Category_Level_Manipulation-main/mani_skill_learn/env/env_utils.py", line 95, in build_env
    return build_from_cfg(cfg, ENVS, default_args)
  File "/data/run01/scv9822/Category_Level_Manipulation-main/mani_skill_learn/utils/meta/registry.py", line 132, in build_from_cfg
    return obj_cls(**args)
  File "/data/run01/scv9822/Category_Level_Manipulation-main/mani_skill_learn/env/env_utils.py", line 60, in make_gym_env
    env = gym.make(env_name, **tmp_kwargs)
  File "/data/run01/scv9822/anaconda3/envs/mani-skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/data/run01/scv9822/anaconda3/envs/mani-skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/data/run01/scv9822/anaconda3/envs/mani-skill/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 349, in __init__
    super().__init__(
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 27, in __init__
    super().__init__(
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/base_env.py", line 93, in __init__
    obs = self.reset(level=0)
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 39, in reset
    super().reset(*args, **kwargs)
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/base_env.py", line 168, in reset
    self._setup_cameras()
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/base_env.py", line 224, in _setup_cameras
    camera = self._load_camera(cam_info)
  File "/data/run01/scv9822/ManiSkill/mani_skill/env/base_env.py", line 211, in _load_camera
    camera = self._scene.add_mounted_camera(
RuntimeError: Vulkan is not initialized
```
but my host is HPC, could it run at HPC?

**Comment by wkwan7** [comment]
Hi,
It is able to run on HPC but it still needs vulkan because we need to capture the visual observation using the cameras in the simulator. See if this helps: `sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils`, also you can check vulkan by  `vulkaninfo`.

**Comment by bio-punk** [comment]
thx for your comment， but HPC user cannot use super user to install software， now I try to run it on a VPS
